import { randomUUID, createHash } from 'node:crypto';
import { Fault, quote, pay, currencies } from './engine.mjs';
const text=(v,min,max)=>typeof v==='string'&&v.trim().length>=min&&v.length<=max;
export const checklistFields=['recipient','invoice','amount','currency'];
function payment(state,id){const p=state.payments.find(p=>p.id===id&&p.mode==='external');if(!p)throw new Fault('External payment not found',404);return p;}
function log(state,action,id){state.audit.unshift({id:randomUUID(),action,reference:id,at:new Date().toISOString(),actor:'Workspace user'});}
export function checklist(state,input){const p=payment(state,input.id);if(!input.checks||checklistFields.some(k=>typeof input.checks[k]!=='boolean'))throw new Fault('Provide all four checklist decisions');p.checklist=Object.fromEntries(checklistFields.map(k=>[k,input.checks[k]]));p.checklistAt=new Date().toISOString();log(state,'Payment checklist updated',p.id);return p.checklist;}
export function reminder(state,input){const p=payment(state,input.id);const time=Date.parse(input.dueAt);if(typeof input.dueAt!=='string'||!Number.isFinite(time))throw new Fault('Choose a valid reminder date');p.reminder={dueAt:new Date(time).toISOString()};log(state,'Payment reminder scheduled',p.id);return p.reminder;}
export function reminders(state,now=Date.now()){return state.payments.filter(p=>p.status==='awaiting_external_payment'&&!p.archivedAt&&p.reminder&&Date.parse(p.reminder.dueAt)<=now).map(p=>({id:p.id,recipient:p.quote.recipient,dueAt:p.reminder.dueAt,provider:p.external.provider.name}));}
export function minor(value,currency){if(typeof value!=='string'||!Object.hasOwn(currencies,currency)||!/^\d+(?:\.\d{1,2})?$/.test(value)||(currencies[currency]===0&&value.includes('.')))throw new Fault('Invalid money amount');const [whole,frac='']=value.split('.');return (BigInt(whole)*10n**BigInt(currencies[currency])+BigInt((frac+'00').slice(0,currencies[currency])||'0')).toString();}
export function cost(state,input){const p=payment(state,input.id);if(typeof input.feeMinor!=='string'||!/^\d{1,12}$/.test(input.feeMinor)||typeof input.receiveMinor!=='string'||!/^\d{1,12}$/.test(input.receiveMinor)||BigInt(input.receiveMinor)===0n)throw new Fault('Provide a nonnegative fee and positive recipient amount in minor units');p.actualCost={feeMinor:input.feeMinor,receiveMinor:input.receiveMinor,feeDifferenceMinor:(BigInt(input.feeMinor)-BigInt(p.quote.feeMinor)).toString(),receiveDifferenceMinor:(BigInt(input.receiveMinor)-BigInt(p.quote.receiveMinor)).toString(),recordedAt:new Date().toISOString(),source:'User reported; not settlement confirmation'};log(state,'Actual provider cost recorded (self-reported)',p.id);return p.actualCost;}
export function invoice(state,input){payment(state,input.paymentId);if(!text(input.name,1,120)||/[\\/\r\n]/.test(input.name)||typeof input.content!=='string'||input.content.length>700000||!/^[A-Za-z0-9+/]+={0,2}$/.test(input.content))throw new Fault('Provide a PDF, PNG, JPEG or TXT file up to 500 KiB');const bytes=Buffer.from(input.content,'base64');if(bytes.length===0||bytes.length>512000||bytes.toString('base64')!==input.content)throw new Fault('Invalid or oversized attachment');const ext=input.name.split('.').pop().toLowerCase();const valid=ext==='pdf'?bytes.subarray(0,5).toString()==='%PDF-':ext==='png'?bytes.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex')):['jpg','jpeg'].includes(ext)?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:ext==='txt'?!bytes.includes(0)&&Buffer.from(bytes.toString('utf8')).equals(bytes):false;if(!valid)throw new Fault('File contents do not match a supported attachment type');state.invoices??=[];if(state.invoices.length>=100)throw new Fault('Workspace attachment limit reached',409);const item={id:randomUUID(),paymentId:input.paymentId,name:input.name,size:bytes.length,sha384:createHash('sha384').update(bytes).digest('hex'),createdAt:new Date().toISOString(),content:input.content};state.invoices.unshift(item);log(state,'Invoice attached',input.paymentId);return {...item,content:undefined};}
export function batch(state,input,key){if(typeof key!=='string'||!/^[\w-]{16,100}$/.test(key))throw new Fault('Batch idempotency key required');if(!Array.isArray(input.rows)||input.rows.length<1||input.rows.length>50||!text(input.name,2,80))throw new Fault('Name the batch and provide 1 to 50 payment rows');const fingerprint=createHash('sha384').update(JSON.stringify(input)).digest('hex');state.batchKeys??={};if(Object.hasOwn(state.batchKeys,key)){const old=state.batchKeys[key];if(old.fingerprint!==fingerprint)throw new Fault('Batch key conflict',409);const previous=state.batches.find(b=>b.id===old.id);if(!previous)throw new Fault('Batch belongs to newer recovery history; inspect safety copy',409);return previous;}
 const next=structuredClone(state),ids=[];for(const r of input.rows){const q=quote(next,{...r,amountMinor:minor(r.amount,r.sourceCurrency)});const p=pay(next,{quoteId:q.id,mode:'external',providerName:input.providerName,providerUrl:input.providerUrl},'batch-'+randomUUID());ids.push(p.id);}const b={id:randomUUID(),name:input.name.trim(),paymentIds:ids,createdAt:new Date().toISOString()};next.batches??=[];next.batches.unshift(b);next.batchKeys[key]={fingerprint,id:b.id};log(next,'External payment batch planned; no funds moved',b.id);Object.assign(state,next);return b;
}
