import test from 'node:test';import assert from 'node:assert/strict';
import { initialState,quote,pay,reserved,review } from './engine.mjs';import { recordReference,lifecycle } from './external.mjs';import { attest,newKeys } from './pqc.mjs';import { reconcileStatement } from './operations.mjs';
function setup(){const s=initialState();s.wallets.USD='0';const q=quote(s,{sourceCurrency:'USD',targetCurrency:'EUR',amountMinor:'1000000',recipient:'Supplier',purpose:'Invoice 123'});return {s,q,body:{quoteId:q.id,mode:'external',providerName:'My bank',providerUrl:'https://example.com/'}};}
test('external handoff does not debit, reserve, settle, or sign a transfer',()=>{const {s,body}=setup();const p=pay(s,body,'external-payment-key-001');assert.equal(p.status,'awaiting_external_payment');assert.equal(s.wallets.USD,'0');assert.equal(reserved(s,'USD'),0n);assert.equal(s.journals.length,0);attest(s,newKeys());assert.equal(p.receipt,undefined);assert.equal(reconcileStatement(s,[]).results.length,0);assert.throws(()=>review(s,p.id,'approve'),/not awaiting review/);});
test('external replay survives serialization and conflicts cannot produce duplicate transfer',()=>{let {s,body}=setup();const p=pay(s,body,'external-payment-key-001');s=JSON.parse(JSON.stringify(s));assert.equal(pay(s,body,'external-payment-key-001').id,p.id);assert.equal(s.payments.length,1);assert.throws(()=>pay(s,{...body,mode:'sandbox'},'external-payment-key-001'),/another request/);assert.throws(()=>pay(s,body,'external-payment-key-002'),/already/);});
test('reference is self-reported and never confirms settlement',()=>{const {s,body}=setup();const p=pay(s,body,'external-payment-key-001');recordReference(s,{id:p.id,reference:'BANK-12345'});assert.equal(p.external.reference,'BANK-12345');assert.equal(p.status,'awaiting_external_payment');assert.match(p.external.confirmation,/unverified/);assert.equal(s.journals.length,0);assert.throws(()=>recordReference(s,{id:p.id,reference:''}));});
test('unsafe provider links and unknown modes fail before creating a record',()=>{for(const url of ['javascript:alert(1)','http://example.com','https://user:pass@example.com','https://127.0.0.1','https://example.com?amount=10','https://example.com/#secret','https://bank.local']){const {s,body}=setup();assert.throws(()=>pay(s,{...body,providerUrl:url},'external-payment-key-001'));assert.equal(s.payments.length,0);}const {s,body}=setup();assert.throws(()=>pay(s,{...body,mode:'settled'},'external-payment-key-001'),/Unknown/);});

test("plan lifecycle retains records and prevents cancellation of referenced plans",()=>{const {s,body}=setup();const p=pay(s,body,"lifecycle-payment-key-001");lifecycle(s,{id:p.id,action:"archive"},"owner");assert.ok(p.archivedAt);lifecycle(s,{id:p.id,action:"unarchive"},"owner");assert.equal(p.archivedAt,undefined);recordReference(s,{id:p.id,reference:"BANK-123"});assert.throws(()=>lifecycle(s,{id:p.id,action:"cancel"},"owner"));delete p.external.reference;lifecycle(s,{id:p.id,action:"cancel"},"owner");assert.equal(p.status,"plan_cancelled");assert.equal(s.payments.length,1);assert.equal(s.journals.length,0);assert.equal(s.wallets.USD,"0");});
