import test from 'node:test';import assert from 'node:assert/strict';import { spawn } from 'node:child_process';import { mkdtemp,readFile,rm } from 'node:fs/promises';import { tmpdir } from 'node:os';import { join } from 'node:path';import { once } from 'node:events';
import { unseal,verifyReceipt,publicKeys } from './pqc.mjs';
import { fileURLToPath } from 'node:url';
test('HTTP PQC and operations integration in isolated temporary workspace',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'atlas-pqc-test-'));let proc;
 try{
  proc=spawn(process.execPath,[fileURLToPath(new URL('./server.mjs',import.meta.url))],{env:{...process.env,PORT:'0',ATLAS_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
  let output='';const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server did not start: '+output)),15000);proc.stdout.on('data',d=>{output+=d;const m=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});proc.stderr.on('data',d=>output+=d);proc.once('exit',()=>{clearTimeout(timer);reject(Error(output));});});
  let state=await (await fetch(base+'/api/state')).json();const post=(path,body={},extra={})=>fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,'X-Sandbox-Token':state.token,...extra},body:JSON.stringify(body)});
  for(const asset of ['/','/app.js','/features.js','/external.js','/style.css'])assert.equal((await fetch(base+asset)).status,200);
  assert.equal((await post('security/export',{}, {'X-Sandbox-Token':'bad'})).status,403);
  const probe=await (await post('security/self-test')).json();assert.equal(probe.kemRoundTrip,true);assert.equal(probe.dualSignature,true);
  assert.equal((await post('beneficiaries',{name:'Northstar vendor',country:'IN',currency:'INR'})).status,200);
  const q=await (await post('quotes',{sourceCurrency:'USD',targetCurrency:'EUR',amountMinor:'10000',recipient:'Northstar vendor',purpose:'PQC test'})).json();
  const key='http-integration-key-001';const request={quoteId:q.id};const r=await post('payments',request,{'Idempotency-Key':key});assert.equal(r.status,200);const p=await r.json();assert.ok(p.receipt);
  const replay=await (await post('payments',request,{'Idempotency-Key':key})).json();assert.equal(replay.id,p.id);
  const inventory=await (await fetch(base+'/api/security')).json();assert.equal(inventory.receipts[0].valid,true);assert.ok(!JSON.stringify(inventory).includes('PRIVATE KEY'));
  const archive=await (await post('security/export')).json();const ring=JSON.parse(await readFile(join(dir,'keyring.json'),'utf8'));const oldKey=ring.keys[0];assert.equal(verifyReceipt(archive.attestation,publicKeys(oldKey)),true);assert.equal(unseal(archive.envelope,oldKey).payments[0].id,p.id);
  assert.equal((await post('security/rotate')).status,200);assert.equal((await (await fetch(base+'/api/security')).json()).keys.length,2);assert.equal((await (await post('security/verify')).json()).receipts[0].valid,true);
  const report=await (await post('reconcile',{rows:[{reference:p.id,currency:'USD',amountMinor:q.totalMinor}]})).json();assert.equal(report.counts.matched,1);
  state=await (await fetch(base+'/api/state')).json();assert.equal(state.beneficiaries.length,1);assert.equal(state.journals.length,1);assert.equal(state.keys,undefined);
  const externalQuote=await (await post('quotes',{sourceCurrency:'USD',targetCurrency:'INR',amountMinor:'100000',recipient:'External supplier',purpose:'External invoice'})).json();
  const externalBody={quoteId:externalQuote.id,mode:'external',providerName:'My bank',providerUrl:'https://example.com/'};
  const externalResponse=await post('payments',externalBody,{'Idempotency-Key':'http-external-key-001'});assert.equal(externalResponse.status,200);const external=await externalResponse.json();assert.equal(external.status,'awaiting_external_payment');assert.equal(external.receipt,undefined);
  const reference=await post('external/reference',{id:external.id,reference:'PROVIDER-REF-123'});assert.equal(reference.status,200);assert.equal((await reference.json()).status,'awaiting_external_payment');
  const latest=await (await fetch(base+'/api/state')).json();assert.equal(latest.wallets.USD,state.wallets.USD);assert.equal(latest.journals.length,1);assert.equal(latest.reserved.USD,'0');
  const register=async(email)=>{const r=await post('accounts/register',{name:'Customer '+email,email,mobile:'+919876543210',password:'secure-passphrase-123'});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];const publicAccount=await r.json();assert.equal(publicAccount.hash,undefined);const current=await (await fetch(base+'/api/state',{headers:{Cookie:cookie}})).json();return {cookie,current};};
  const a=await register('a@example.com'),b=await register('b@example.com');
  const scoped=(a,path,body)=>fetch(base+'/api/'+path,{method:'POST',headers:{Cookie:a.cookie,Origin:base,'Content-Type':'application/json','X-Sandbox-Token':a.current.token,'Idempotency-Key':'customer-plan-key-001'},body:JSON.stringify(body)});
  const aq=await (await scoped(a,'quotes',{sourceCurrency:'USD',targetCurrency:'EUR',amountMinor:'10000',recipient:'Private vendor',purpose:'Private invoice'})).json();const ap=await (await scoped(a,'payments',{quoteId:aq.id,mode:'external',providerName:'Wise',providerUrl:'https://wise.com/'})).json();
  const attachment=await scoped(a,'business/invoice',{paymentId:ap.id,name:'invoice.txt',content:Buffer.from('Private invoice').toString('base64')});assert.equal(attachment.status,200);const item=await attachment.json();assert.equal(item.content,undefined);
  assert.equal((await fetch(base+'/api/invoices/'+item.id,{headers:{Cookie:b.cookie}})).status,404);const download=await fetch(base+'/api/invoices/'+item.id,{headers:{Cookie:a.cookie}});assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/^attachment/);assert.equal(await download.text(),'Private invoice');
  assert.equal((await scoped(b,'business/checklist',{id:ap.id,checks:{recipient:true,invoice:true,amount:true,currency:true}})).status,404);
  assert.equal((await scoped(a,'business/checklist',{id:ap.id,checks:{recipient:true,invoice:true,amount:true,currency:true}})).status,200);
  assert.equal((await scoped(a,'business/reminder',{id:ap.id,dueAt:'2020-01-01T00:00:00Z'})).status,200);
  const accountA=await (await fetch(base+'/api/state',{headers:{Cookie:a.cookie}})).json();assert.equal(accountA.reminders.length,1);assert.equal(accountA.invoices[0].content,undefined);assert.equal(accountA.workspace.id,a.current.workspace.id);
  const accountB=await (await fetch(base+'/api/state',{headers:{Cookie:b.cookie}})).json();assert.equal(accountB.payments.length,0);assert.equal(accountB.invoices.length,0);
  assert.equal((await scoped(a,'provider/check',{id:ap.id,transferId:'123',recipientId:'456'})).status,503);
  assert.equal((await post('accounts/login',{email:'a@example.com',password:'incorrect'})).status,401);
  const login=await post('accounts/login',{email:'a@example.com',password:'secure-passphrase-123'});assert.equal(login.status,200);
  const loggedCookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await (await fetch(base+'/api/state',{headers:{Cookie:loggedCookie}})).json()).payments[0].id,ap.id);
  assert.equal((await scoped(a,'team/member',{email:'b@example.com',role:'approver'})).status,200);
  assert.equal((await scoped(b,'accounts/switch',{workspaceId:a.current.workspace.id})).status,200);
  assert.equal((await scoped(a,'approval',{id:ap.id,decision:'request'})).status,200);
  assert.equal((await scoped(a,'approval',{id:ap.id,decision:'approve'})).status,403);
  const approved=await scoped(b,'approval',{id:ap.id,decision:'approve'});assert.equal(approved.status,200);assert.equal((await approved.json()).status,'approved');
  assert.equal((await scoped(a,'team/member',{email:'b@example.com',role:'viewer'})).status,200);
  assert.equal((await scoped(b,'quotes',{sourceCurrency:'USD',targetCurrency:'EUR',amountMinor:'1000',recipient:'No write',purpose:'Read-only test'})).status,403);
  const snapshot=await (await scoped(a,'backup/export',{})).json();
  assert.equal((await scoped(b,'backup/preview',{archive:snapshot})).status,403);
  const preview=await (await scoped(a,'backup/preview',{archive:snapshot})).json();assert.ok(preview.previewId);
  assert.equal((await scoped(a,'business/cost',{id:ap.id,feeMinor:'150',receiveMinor:'9100'})).status,200);
  assert.equal((await scoped(a,'backup/restore',{previewId:preview.previewId})).status,409);
  const fresh=await (await scoped(a,'backup/preview',{archive:snapshot})).json();const restored=await scoped(a,'backup/restore',{previewId:fresh.previewId});assert.equal(restored.status,200);assert.match((await restored.json()).safetyCopy,/^recovery-/);
  const afterRestore=await (await fetch(base+'/api/state',{headers:{Cookie:a.cookie}})).json();assert.equal(afterRestore.payments[0].actualCost,undefined);assert.equal(afterRestore.payments[0].approval.status,'approved');
 }finally{if(proc && proc.exitCode===null){const exited=once(proc,'exit');proc.kill();await exited;}await rm(dir,{recursive:true,force:true});}
});
