import test from 'node:test';
import assert from 'node:assert/strict';
import { newKeys, publicKeys, seal, unseal, signReceipt, verifyReceipt, attest, checkPayments } from './pqc.mjs';
import { initialState, quote, pay, review, available, reserved } from './engine.mjs';
import { beneficiary, reconcileStatement } from './operations.mjs';
const keys=newKeys(),pub=publicKeys(keys);
const input=amountMinor=>({sourceCurrency:'USD',targetCurrency:'EUR',amountMinor,recipient:'Acme',purpose:'Invoice'});
function payment(s,amount='10000',key='test-payment-key-001'){const q=quote(s,input(amount));return pay(s,{quoteId:q.id},key);}
test('native ML-KEM encryption round trip and fresh ciphertext each time',()=>{const p={recipient:'Acme',amountMinor:'10000'};const a=seal(p,keys),b=seal(p,keys);assert.deepEqual(unseal(a,keys),p);assert.notEqual(a.kemCiphertext,b.kemCiphertext);assert.notEqual(a.iv,b.iv);assert.ok(!JSON.stringify(a).includes('Acme'));});
test('encrypted exports reject modified content, header, tag, and wrong keys',()=>{const e=seal({secret:'private'},keys);for(const field of ['ciphertext','tag','kemCiphertext','salt','iv']){const modified=structuredClone(e);const b=Buffer.from(modified[field],'base64');b[0]^=1;modified[field]=b.toString('base64');assert.throws(()=>unseal(modified,keys),field);}assert.throws(()=>unseal(e,newKeys()));});
test('both receipt signatures required; payload tampering fails',()=>{const r=signReceipt({amount:'100',id:'p1'},keys);assert.equal(verifyReceipt(r,pub),true);for(const field of ['mlDsa','ed25519']){const bad=structuredClone(r);bad[field]=Buffer.alloc(10).toString('base64');assert.equal(verifyReceipt(bad,pub),false);}const bad=structuredClone(r);bad.payload.amount='101';assert.equal(verifyReceipt(bad,pub),false);assert.equal(verifyReceipt(r,publicKeys(newKeys())),false);});
test('receipt inventory detects current payment and journal tampering',()=>{const s=initialState();const p=payment(s);attest(s,keys);assert.equal(checkPayments(s,[keys])[0].valid,true);p.quote.recipient='Other';assert.equal(checkPayments(s,[keys])[0].valid,false);p.quote.recipient='Acme';s.journals[0].postings[0].debit='1';assert.equal(checkPayments(s,[keys])[0].valid,false);});
test('retained key verifies old receipt after active key changes',()=>{const s=initialState();payment(s);attest(s,keys);const newer=newKeys();payment(s,'10000','test-payment-key-002');attest(s,newer);assert.ok(checkPayments(s,[keys,newer]).every(r=>r.valid));assert.equal(checkPayments(s,[newer]).filter(r=>r.valid).length,1);});
test('review reserves available balance and rejection releases it',()=>{const s=initialState(),p=payment(s,'1000000');assert.equal(reserved(s,'USD'),1003600n);assert.equal(available(s,'USD'),11496400n);assert.throws(()=>payment(s,'12000000','test-payment-key-002'),/Insufficient/);review(s,p.id,'reject');assert.equal(available(s,'USD'),12500000n);});
test('approval consumes only its reservation without stealing another hold',()=>{const s=initialState(),a=payment(s,'1000000'),b=payment(s,'1000000','test-payment-key-002');review(s,a.id,'approve');assert.equal(s.wallets.USD,'11496400');assert.equal(reserved(s,'USD'),1003600n);assert.equal(available(s,'USD'),10492800n);review(s,b.id,'approve');assert.equal(s.wallets.USD,'10492800');});
test('saved recipients validate and deduplicate',()=>{const s=initialState();beneficiary(s,{name:'Acme',country:'IN',currency:'INR'});assert.throws(()=>beneficiary(s,{name:'ACME',country:'IN',currency:'INR'}),/already/);assert.throws(()=>beneficiary(s,{name:'Other',country:'India',currency:'INR'}));assert.throws(()=>beneficiary(s,{name:'Other',country:'IN',currency:'constructor'}));assert.throws(()=>quote(s,{...input('100'),sourceCurrency:['USD']}));assert.throws(()=>beneficiary(s,{name:'Other',country:'IN',currency:['INR']}));});
test('reconciliation detects matches, duplicate, mismatch, missing and unexpected',()=>{const s=initialState(),a=payment(s),b=payment(s,'20000','test-payment-key-002');payment(s,'30000','test-payment-key-003');const row={reference:a.id,currency:'USD',amountMinor:a.quote.totalMinor};const report=reconcileStatement(s,[row,row,{reference:b.id,currency:'EUR',amountMinor:b.quote.totalMinor},{reference:'external',currency:'USD',amountMinor:'100'}]);assert.deepEqual(report.counts,{matched:1,duplicate:1,mismatch:1,unexpected:1,missing:1});assert.throws(()=>reconcileStatement(s,[{reference:a.id,currency:'USD',amountMinor:'-1'}]));});
