export function nextStep(p,context){
 const label=(title,view,detail)=>({title,view,detail});
 if(context.role==='viewer')return label('View payment history','history','Read-only access; ask a preparer or approver to take the next action');
 if(p.mode!=='external')return p.status==='review'?label('Review sandbox payment','reviews','Demo funds only'):label('Inspect sandbox record','ledger','Simulated settlement; no real funds moved');
 if(p.status==='external_failed')return label('Investigate provider failure','integrations','Check the latest provider status before retrying');
 if(p.status==='external_sent')return label('Track provider delivery','integrations','Provider reports sent; recipient credit is not confirmed');
 if(!['recipient','invoice','amount','currency'].every(k=>p.checklist?.[k]))return label('Complete payment checklist','operations','Check recipient, invoice, amount and currencies');
 if(p.approval?.status==='rejected')return label('Review rejected plan','team','Discuss the rejection before resubmitting');
 if(p.approval?.status!=='approved'){
  if(context.workspaceId==='demo')return label('Create a customer workspace','accounts','Independent approvals require separate signed-in team members');
  if(p.approval?.status==='pending')return label('Await independent approval','team',p.preparedBy===context.actor||p.approval.requestedBy===context.actor?'Another member must decide':context.role==='approver'||context.role==='owner'?'You can review this plan':'Ask an owner or approver to review');
  return label('Submit for team approval','team','Approval does not initiate a transfer');
 }
 if(!p.external.reference)return label('Pay in your provider app','external','Use the provider’s actual quote, then record its reference');
 if(p.providerConfirmation?.environment==='live')return label('Recheck live provider status','integrations','The provider has not yet reported this payment sent');
 return context.integration.configured&&p.external.provider.name.toLowerCase()==='wise'?label('Verify provider status','integrations','Check the transfer and recipient IDs'):label('Track external payment','integrations','A recorded reference is self-reported; provider credentials are required for verification');
}
export function readiness(state,context){const customer=context.workspaceId!=='demo';const members=context.members||[];const steps=[{title:'Use a customer workspace',done:customer,view:'accounts',detail:customer?'Customer sandbox; email and business identity are not verified':'Shared local demo workspace'},{title:'Save a recipient',done:!!state.beneficiaries?.length,view:'beneficiaries',detail:'Recipient records are not automatic bank-detail verification'},{title:'Prepare a payment plan',done:state.payments.some(p=>p.mode==='external'),view:'providers',detail:'Create a quote and select a provider handoff'},{title:'Add an independent approver',done:customer&&members.some(m=>m.id!==context.actor&&['owner','approver'].includes(m.role)),view:'team',detail:'A different person must approve the plan'},{title:'Connect provider status',done:context.integration.configured,view:'integrations',detail:context.integration.configured?'Read-only '+context.integration.environment+' API connection':'Provider credentials are not configured'}];return {workspaceId:context.workspaceId,workspaceName:context.name,role:context.role,userEmail:context.email||null,mode:'Local sandbox',steps,completed:steps.filter(s=>s.done).length,total:steps.length,integration:context.integration,payments:state.payments.map(p=>({id:p.id,recipient:p.quote.recipient,status:p.status,evidence:p.mode!=='external'?'Demo funds / simulated settlement':p.providerConfirmation?.environment==='live'?'Authenticated live provider status':p.providerConfirmation?'Provider sandbox test evidence':'External plan / unverified',next:nextStep(p,context)})),limits:['All AtlasPay wallet balances are demo funds','FX quotes are illustrative; use the provider’s actual quote','PQC protects receipts and encrypted archives, not local HTTP transport','Email verification and password recovery require configured email delivery; authenticator MFA is available. Mobile SMS verification is not connected']};}
