import http from 'node:http';import { pathToFileURL } from 'node:url';import { resolve,sep } from 'node:path';import { readFile,writeFile,mkdir,rename } from 'node:fs/promises';import { randomBytes,timingSafeEqual } from 'node:crypto';
import { initialState,quote,pay,review,Fault,available,reserved } from './engine.mjs';
import { newKeys,publicKeys,attest,checkPayments,seal,unseal,signReceipt,verifyReceipt } from './pqc.mjs';
import { beneficiary,reconcileStatement } from './operations.mjs';import { recordReference,lifecycle } from './external.mjs';
import { checklist,reminder,reminders,cost,invoice,batch } from './business.mjs';import { createAccount,authenticate,accountPublic,mobileNumber } from './accounts.mjs';import { integrationStatus,checkProvider } from './provider.mjs';
import { tagPlans,approve,duplicates,invoiceNumber,search,forecast,template,runTemplate,accounting,backup,previewBackup } from './workflows.mjs';import { createHash,randomUUID } from 'node:crypto';
const recoveryPreviews=new Map();
import { readiness } from './readiness.mjs';
import {sendToken,tokenHash,newPassword,createEnrollment,verifyTotp,recoveryCodes,verifyFactor} from './auth-security.mjs';const enrollments=new Map();
const data=process.env.ATLAS_DATA_DIR?pathToFileURL(resolve(process.env.ATLAS_DATA_DIR)+sep):new URL('../.sandbox/',import.meta.url);await mkdir(data,{recursive:true});
async function readJson(name,fallback){try{return JSON.parse(await readFile(new URL(name,data),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;return fallback;}}
async function writeJson(name,body){const tmp=new URL(name+'.tmp',data);await writeFile(tmp,JSON.stringify(body,null,2),{mode:0o600});await rename(tmp,new URL(name,data));}
let accounts=await readJson('accounts.json',[]);const states=new Map([['demo',await readJson('state.json',initialState())]]);const sessions=new Map();
let keyring=await readJson('keyring.json',null);if(!keyring){if(accounts.length||states.get('demo').payments.some(p=>p.receipt))throw Error('PQC keyring missing; restore original keyring');keyring={active:0,keys:[newKeys()]};await writeJson('keyring.json',keyring);}
const activeKey=()=>keyring.keys[keyring.active];const token=randomBytes(32).toString('hex');
const IDLE_MS=30*60*1000;
function sameToken(a,b){return typeof a==='string'&&typeof b==='string'&&a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));}
const filename=id=>id==='demo'?'state.json':'workspace-'+id+'.json';
async function workspace(id){if(!states.has(id))states.set(id,await readJson(filename(id),initialState()));return states.get(id);}
async function save(next,id){attest(next,activeKey());await writeJson(filename(id),next);states.set(id,next);}
await save(structuredClone(states.get('demo')),'demo');
function security(state){return {mode:'Local sandbox',runtime:process.version,signature:'ML-DSA-65 + Ed25519 (both required)',encryption:'ML-KEM-768 / HKDF-SHA384 / AES-256-GCM',activeKeyId:activeKey().id,keys:keyring.keys.map(publicKeys),receipts:checkPayments(state,keyring.keys),transport:'Loopback HTTP; no PQC transport claim',keyStorage:'Local keyring file; no HSM/KMS',stateStorage:'Local JSON; plaintext'};}
function session(req){const cookie=req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('atlas_session='))?.slice(14);const s=sessions.get(cookie);if(s&&s.expiresAt>Date.now()&&Date.now()-Date.parse(s.lastSeenAt)<IDLE_MS){s.lastSeenAt=new Date().toISOString();return {...s,cookie};}if(cookie)sessions.delete(cookie);return {workspaceId:'demo',token};}
function accountEvent(a,type){a.securityAlerts??=[];a.securityAlerts.unshift({id:randomUUID(),type,at:new Date().toISOString()});a.securityAlerts=a.securityAlerts.slice(0,100);}
async function issue(res,a,req){const list=structuredClone(accounts),target=list.find(x=>x.id===a.id);accountEvent(target,'New sign-in');await writeJson('accounts.json',list);accounts=list;const prior=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('atlas_session='))?.slice(14);if(prior)sessions.delete(prior);for(const [key,value]of sessions)if(value.expiresAt<=Date.now()||Date.now()-Date.parse(value.lastSeenAt)>=IDLE_MS)sessions.delete(key);const cookie=randomBytes(32).toString('hex');sessions.set(cookie,{id:randomUUID(),createdAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),device:String(req.headers['user-agent']||'Unknown browser').slice(0,200),workspaceId:a.id,accountId:a.id,token:randomBytes(32).toString('hex'),expiresAt:Date.now()+8*3600000});res.setHeader('Set-Cookie','atlas_session='+cookie+'; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800');return accountPublic(a);}
let queue=Promise.resolve();const limits=new Map();const enqueue=fn=>{const pending=queue.then(fn);queue=pending.catch(()=>{});return pending;};
const isCloud = !!(process.env.NODE_ENV === 'production' || process.env.VERCEL || process.env.RENDER || (process.env.PORT && process.env.PORT !== '8080'));
const server=http.createServer(async(req,res)=>{
 const host=req.headers.host;if(!isCloud && !/^127\.0\.0\.1:\d+$/.test(host||'')){res.writeHead(403);return res.end('Loopback host required');}
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'; object-src 'none'");
 res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('X-Frame-Options','DENY');
 const url=new URL(req.url,'http://'+host),s=session(req),id=s.workspaceId;const json=(status,body)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(body));};
 try{
  let user=accounts.find(a=>a.id===s.accountId);const role=id==='demo'?'owner':user?.id===id?'owner':user?.memberships?.find(m=>m.workspaceId===id)?.role;if(!role)throw new Fault('Workspace access revoked',403);const actor=user?.id||'demo';
  if(req.method==='GET'){
   if(url.pathname==='/health')return json(200,{ok:true,mode:'sandbox',version:'0.8.1'});
   const assets={'/':'dashboard.html','/app.js':'app.js','/pricing.js':'pricing.js','/features.js':'features.js','/external.js':'external.js','/business.js':'business.js','/workflows.js':'workflows.js','/readiness.js':'readiness.js','/account-security.js':'account-security.js','/style.css':'style.css'};
   if(Object.hasOwn(assets,url.pathname)){res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript':url.pathname.endsWith('.css')?'text/css':'text/html');return res.end(await readFile(new URL('../apps/web/'+assets[url.pathname],import.meta.url)));}
   const state=await workspace(id);
   if(url.pathname==='/api/accounts/activity'){if(!user)throw new Fault('Sign in to view account activity',401);return json(200,{sessions:[...sessions.values()].filter(x=>x.accountId===actor&&x.expiresAt>Date.now()).map(x=>({id:x.id,device:x.device,createdAt:x.createdAt,lastSeenAt:x.lastSeenAt,expiresAt:new Date(x.expiresAt).toISOString(),current:x.id===s.id})),alerts:user.securityAlerts||[],delivery:'In-app history only; email and push alerts are not connected'});}
   if(url.pathname==='/api/profile')return json(200,user?accountPublic(user):null);
   if(url.pathname==='/api/readiness')return json(200,readiness(state,{workspaceId:id,actor,role,name:accounts.find(a=>a.id===id)?.name||'Northstar Studio',email:user?.email,integration:integrationStatus(id),members:accounts.filter(a=>a.id===id||a.memberships?.some(m=>m.workspaceId===id)).map(a=>({id:a.id,role:a.id===id?'owner':a.memberships.find(m=>m.workspaceId===id).role}))}));
   if(url.pathname==='/api/workflows')return json(200,{role,userId:actor,workspaces:user?[{id:user.id,name:user.name,role:'owner'},...(user.memberships||[]).map(m=>({...m,name:accounts.find(a=>a.id===m.workspaceId)?.name||'Workspace'}))]:[{id:'demo',name:'Local demo',role:'owner'}],members:role==='owner'?accounts.filter(a=>a.id===id||a.memberships?.some(m=>m.workspaceId===id)).map(a=>({id:a.id,email:a.email,role:a.id===id?'owner':a.memberships.find(m=>m.workspaceId===id).role})):[],duplicates:duplicates(state)});
   if(url.pathname==='/api/state'){const a=accounts.find(a=>a.id===id);return json(200,{...state,keys:undefined,batchKeys:undefined,quotes:undefined,invoices:(state.invoices||[]).map(i=>({...i,content:undefined})),workspace:a?accountPublic(a):{id:'demo',name:'Northstar Studio',email:null},token:s.token,reminders:reminders(state),available:Object.fromEntries(Object.keys(state.wallets).map(c=>[c,available(state,c).toString()])),reserved:Object.fromEntries(Object.keys(state.wallets).map(c=>[c,reserved(state,c).toString()]))});}
   if(url.pathname==='/api/security')return json(200,security(state));
   if(url.pathname==='/api/integrations')return json(200,integrationStatus(id));
   if(url.pathname.startsWith('/api/invoices/')){const item=state.invoices?.find(i=>i.id===url.pathname.slice(14));if(!item)throw new Fault('Attachment not found in this workspace',404);res.setHeader('Content-Type','application/octet-stream');res.setHeader('Content-Disposition',"attachment; filename*=UTF-8''"+encodeURIComponent(item.name));return res.end(Buffer.from(item.content,'base64'));}
   return json(404,{error:'Not found'});
  }
  if(req.method!=='POST')return json(405,{error:'Method not allowed'});
  const validOrigin = !req.headers.origin || req.headers.origin==='http://'+host || req.headers.origin==='https://'+host;
  if(!validOrigin||!sameToken(req.headers['x-sandbox-token'],s.token))throw new Fault('Invalid session or origin',403);
  const minute=Math.floor(Date.now()/60000),limKey=minute+':'+(url.pathname.startsWith('/api/accounts/')?'auth':'ops');const count=limits.get(limKey)||0;if(count>=(limKey.endsWith('auth')?10:100))throw new Fault('Too many requests; try again next minute',429);for(const k of limits.keys())if(!k.startsWith(minute+':'))limits.delete(k);limits.set(limKey,count+1);
  if(!req.headers['content-type']?.startsWith('application/json'))throw new Fault('JSON required',415);const max=url.pathname==='/api/backup/preview'?75000000:url.pathname==='/api/business/invoice'?800000:65536;const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw new Fault('Request too large',413);chunks.push(chunk);}let input;try{input=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(chunks)));}catch{throw new Fault('Invalid JSON');}if(!input||typeof input!=='object'||Array.isArray(input))throw new Fault('Invalid request');
  const result=await enqueue(async()=>{
   if(s.cookie&&(!sessions.has(s.cookie)||sessions.get(s.cookie).expiresAt<=Date.now()||sessions.get(s.cookie).workspaceId!==id||Date.now()-Date.parse(sessions.get(s.cookie).lastSeenAt)>=IDLE_MS))throw new Fault('Session ended; sign in again',401);
   user=accounts.find(a=>a.id===s.accountId);
   if(user){const currentRole=user.id===id?'owner':user.memberships?.find(m=>m.workspaceId===id)?.role;if(currentRole!==role)throw new Fault('Workspace access changed; reload',403);}
   if(url.pathname==='/api/accounts/sessions/revoke'){if(!user)throw new Fault('Sign in first',401);if(input.allOthers!==true&&typeof input.id!=='string')throw new Fault('Choose a session');const matches=[...sessions.entries()].filter(([key,value])=>value.accountId===actor&&key!==s.cookie&&(input.allOthers===true||value.id===input.id));if(input.allOthers!==true&&!matches.length)throw new Fault('Other active session not found',404);const list=structuredClone(accounts);accountEvent(list.find(a=>a.id===actor),'Other sessions signed out');await writeJson('accounts.json',list);accounts=list;for(const [key]of matches)sessions.delete(key);return {message:matches.length+' other session(s) signed out'};}

   if(url.pathname==='/api/accounts/register'){const a=await createAccount(accounts,input);const nextAccounts=[...accounts,a];await save(initialState(),a.id);await writeJson('accounts.json',nextAccounts);accounts=nextAccounts;return issue(res,a,req);}
   if(url.pathname==='/api/accounts/login'){const a=await authenticate(accounts,input);if(a.mfaSecret){const list=structuredClone(accounts);verifyFactor(list.find(x=>x.id===a.id),input);await writeJson('accounts.json',list);accounts=list;}return issue(res,a,req);}
   if(url.pathname==='/api/accounts/reset-request'){const a=accounts.find(a=>a.email===String(input.email).trim().toLowerCase());if(a){let ticket;try{ticket=await sendToken(a,'reset',data);}catch(e){if(!(e instanceof Fault)||e.status!==503)throw e;}if(ticket){const list=structuredClone(accounts);list.find(x=>x.id===a.id).resetTicket=ticket;await writeJson('accounts.json',list);accounts=list;}}return {message:'If the account exists, recovery instructions have been prepared. Check email when configured, otherwise the local developer mail-outbox.'};}
   if(url.pathname==='/api/accounts/reset-complete'){const a=accounts.find(a=>a.email===String(input.email).trim().toLowerCase());if(typeof input.token!=='string'||input.token.length!==64||!a?.resetTicket||a.resetTicket.expiresAt<Date.now()||!sameToken(a.resetTicket.hash,tokenHash(input.token)))throw new Fault('Invalid or expired recovery token',400);const list=structuredClone(accounts),target=list.find(x=>x.id===a.id);await newPassword(target,input.password);delete target.resetTicket;accountEvent(target,'Password changed through recovery');await writeJson('accounts.json',list);accounts=list;for(const [key,value]of sessions)if(value.accountId===a.id)sessions.delete(key);return {message:'Password changed. Sign in again; MFA remains enabled if configured.'};}
   if(url.pathname==='/api/accounts/verify-request'){if(!user)throw new Fault('Sign in first',401);const ticket=await sendToken(user,'verify',data);const list=structuredClone(accounts);list.find(x=>x.id===actor).verifyTicket=ticket;await writeJson('accounts.json',list);accounts=list;return {mode:ticket.mode,message:ticket.mode==='email'?'Verification email accepted by the email service':'Development token saved in .sandbox/mail-outbox; no email sent'};}
   if(url.pathname==='/api/accounts/verify-complete'){if(!user)throw new Fault('Sign in first',401);if(typeof input.token!=='string'||input.token.length!==64||!user.verifyTicket||user.verifyTicket.expiresAt<Date.now()||!sameToken(user.verifyTicket.hash,tokenHash(input.token)))throw new Fault('Invalid or expired verification token');const list=structuredClone(accounts),target=list.find(x=>x.id===actor);target.emailVerificationMode=target.verifyTicket.mode;if(target.verifyTicket.mode==='email')target.emailVerifiedAt=new Date().toISOString();delete target.verifyTicket;await writeJson('accounts.json',list);accounts=list;return accountPublic(target);}
   if(url.pathname==='/api/accounts/mfa-start'){if(!user)throw new Fault('Sign in first',401);await authenticate(accounts,{email:user.email,password:input.password});if(user.mfaSecret)throw new Fault('MFA already enabled',409);const enrollment=createEnrollment(user.email);enrollments.set(actor,enrollment);return enrollment;}
   if(url.pathname==='/api/accounts/mfa-enable'){if(!user)throw new Fault('Sign in first',401);const enrollment=enrollments.get(actor);if(!enrollment||enrollment.expiresAt<Date.now())throw new Fault('Enrollment expired');const step=verifyTotp(enrollment.secret,input.code);const list=structuredClone(accounts),target=list.find(x=>x.id===actor);target.mfaSecret=enrollment.secret;target.mfaLastStep=step;const codes=recoveryCodes(target);accountEvent(target,url.pathname.endsWith('mfa-enable')?'MFA enabled':'MFA recovery codes replaced');await writeJson('accounts.json',list);accounts=list;enrollments.delete(actor);for(const [key,value]of sessions)if(value.accountId===actor)sessions.delete(key);return {codes,message:'MFA enabled. Save these single-use recovery codes privately. Sign in again.'};}
   if(url.pathname==='/api/accounts/mfa-disable'){if(!user||!user.mfaSecret)throw new Fault('MFA is not enabled');await authenticate(accounts,{email:user.email,password:input.password});const list=structuredClone(accounts),target=list.find(x=>x.id===actor);verifyFactor(target,input);delete target.mfaSecret;delete target.mfaLastStep;delete target.recoveryHashes;accountEvent(target,'MFA disabled');await writeJson('accounts.json',list);accounts=list;for(const [key,value]of sessions)if(value.accountId===actor)sessions.delete(key);return {message:'MFA disabled. Sign in again.'};}
   if(url.pathname==='/api/accounts/mfa-recovery'){if(!user?.mfaSecret)throw new Fault('Enable MFA first');await authenticate(accounts,{email:user.email,password:input.password});const list=structuredClone(accounts),target=list.find(x=>x.id===actor);verifyFactor(target,input);const codes=recoveryCodes(target);accountEvent(target,url.pathname.endsWith('mfa-enable')?'MFA enabled':'MFA recovery codes replaced');await writeJson('accounts.json',list);accounts=list;return {codes,message:'New codes created. All previous recovery codes are invalid.'};}
   if(url.pathname==='/api/accounts/logout'){if(s.cookie)sessions.delete(s.cookie);res.setHeader('Set-Cookie','atlas_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return {ok:true};}
   if(url.pathname==='/api/accounts/profile'){if(!user)throw new Fault('Sign in to update your mobile number',401);const number=mobileNumber(input.mobile),list=structuredClone(accounts);list.find(a=>a.id===actor).mobile=number;await writeJson('accounts.json',list);accounts=list;return accountPublic(list.find(a=>a.id===actor));}
   if(url.pathname==='/api/accounts/switch'){if(!user||!s.cookie||(input.workspaceId!==user.id&&!user.memberships?.some(m=>m.workspaceId===input.workspaceId)))throw new Fault('Workspace access denied',403);sessions.get(s.cookie).workspaceId=input.workspaceId;return {ok:true};}
   if(url.pathname==='/api/team/member'){if(role!=='owner'||id==='demo')throw new Fault('Sign in as the customer workspace owner',403);if(!['preparer','approver','viewer'].includes(input.role))throw new Fault('Invalid role');const list=structuredClone(accounts),a=list.find(a=>a.email===String(input.email).trim().toLowerCase());if(!a||a.id===id)throw new Fault('Add another registered customer account by email');a.memberships??=[];a.memberships=a.memberships.filter(m=>m.workspaceId!==id);a.memberships.push({workspaceId:id,role:input.role});await writeJson('accounts.json',list);accounts=list;return {email:a.email,role:input.role};}
   const liveUser=accounts.find(a=>a.id===actor);const liveRole=id==='demo'?'owner':liveUser?.id===id?'owner':liveUser?.memberships?.find(m=>m.workspaceId===id)?.role;if(liveRole!==role)throw new Fault('Workspace role changed; reload and try again',403);const readRoutes=['/api/accounting/export','/api/search','/api/forecast','/api/backup/export','/api/security/verify','/api/security/self-test','/api/security/export'];if(role==='viewer'&&!readRoutes.includes(url.pathname))throw new Fault('This workspace role is read-only',403);
   if(['/api/backup/preview','/api/backup/restore'].includes(url.pathname)&&role!=='owner')throw new Fault('Workspace owner required',403);
   const next=structuredClone(await workspace(id));let result;
   const previous=new Set(next.payments.map(p=>p.id));
   if(url.pathname==='/api/accounting/export')return accounting(next,input);
   if(url.pathname==='/api/search')return search(next,input);
   if(url.pathname==='/api/forecast')return forecast(next,input);
   if(url.pathname==='/api/backup/export')return backup(next,id,activeKey());
   if(url.pathname==='/api/backup/preview'){const restored=previewBackup(input.archive,id,keyring.keys);const previewId=randomUUID(),revision=createHash('sha384').update(JSON.stringify(next)).digest('hex');for(const [key,value] of recoveryPreviews)if(value.expiresAt<Date.now()||(value.actor===actor&&value.workspaceId===id))recoveryPreviews.delete(key);recoveryPreviews.set(previewId,{workspaceId:id,actor,restored,revision,expiresAt:Date.now()+300000});return {previewId,createdAt:restored.createdAt,payments:restored.state.payments.length,invoices:restored.state.invoices?.length||0,currentPayments:next.payments.length,warning:'Restores this sandbox snapshot. Current state is saved as an encrypted safety copy. Newer records are replaced.'};}
   if(url.pathname==='/api/backup/restore'){const p=recoveryPreviews.get(input.previewId);if(!p||p.workspaceId!==id||p.actor!==actor||p.expiresAt<Date.now()||p.revision!==createHash('sha384').update(JSON.stringify(next)).digest('hex'))throw new Fault('Preview expired or workspace changed; preview again',409);const safety='recovery-'+randomUUID()+'.json';await writeJson(safety,backup(next,id,activeKey()));const recovered=structuredClone(p.restored.state);recovered.keys={...recovered.keys,...next.keys};recovered.batchKeys={...recovered.batchKeys,...next.batchKeys};for(const item of recovered.payments){const latest=next.payments.find(q=>q.id===item.id);if(latest?.providerConfirmation){item.providerConfirmation=latest.providerConfirmation;item.status=latest.status;item.external=latest.external;}}recovered.audit.unshift({id:randomUUID(),action:'Workspace recovered from verified backup; safety copy '+safety,reference:id,at:new Date().toISOString(),actor});await save(recovered,id);recoveryPreviews.delete(input.previewId);return {ok:true,safetyCopy:safety};}
   if(url.pathname==='/api/quotes')result=quote(next,input);
   else if(url.pathname==='/api/payments')result=pay(next,input,req.headers['idempotency-key']);
   else if(url.pathname==='/api/review'){if(!['owner','approver'].includes(role))throw new Fault('Approver role required',403);result=review(next,input.id,input.decision);}
   else if(url.pathname==='/api/external/lifecycle')result=lifecycle(next,input,actor);
   else if(url.pathname==='/api/external/reference')result=recordReference(next,input);
   else if(url.pathname==='/api/beneficiaries')result=beneficiary(next,input);
   else if(url.pathname==='/api/reconcile'){result=reconcileStatement(next,input.rows);next.reconciliation=result;}
   else if(url.pathname==='/api/business/checklist')result=checklist(next,input);
   else if(url.pathname==='/api/business/reminder')result=reminder(next,input);
   else if(url.pathname==='/api/business/cost')result=cost(next,input);
   else if(url.pathname==='/api/business/invoice')result=invoice(next,input);
   else if(url.pathname==='/api/business/batch')result=batch(next,input,req.headers['idempotency-key']);
   else if(url.pathname==='/api/provider/check')result=await checkProvider(next,input,id);
   else if(url.pathname==='/api/approval')result=approve(next,input,actor,role);
   else if(url.pathname==='/api/invoice-number')result=invoiceNumber(next,input);
   else if(url.pathname==='/api/templates/create')result=template(next,input);
   else if(url.pathname==='/api/templates/run')result=runTemplate(next,input);
   else if(url.pathname==='/api/security/verify')return security(next);
   else if(url.pathname==='/api/security/self-test'){const probe={challenge:randomBytes(32).toString('hex')};const envelope=seal(probe,activeKey());return {kemRoundTrip:unseal(envelope,activeKey()).challenge===probe.challenge,dualSignature:verifyReceipt(signReceipt(probe,activeKey()),publicKeys(activeKey())),at:new Date().toISOString()};}
   else if(url.pathname==='/api/security/export'){const {keys,quotes,batchKeys,...records}=next;const envelope=seal({mode:'sandbox',workspaceId:id,at:new Date().toISOString(),...records},activeKey());return {envelope,attestation:signReceipt(envelope,activeKey()),publicKey:publicKeys(activeKey())};}
   else if(url.pathname==='/api/security/rotate'){if(id!=='demo')throw new Fault('Key rotation is available in the local demo administrator workspace',403);const ring=structuredClone(keyring);ring.keys.push(newKeys());ring.active=ring.keys.length-1;await writeJson('keyring.json',ring);keyring=ring;next.audit.unshift({id:randomBytes(16).toString('hex'),action:'PQC keys rotated; prior keys retained',reference:activeKey().id,at:new Date().toISOString(),actor:'Local demo administrator'});result={activeKeyId:activeKey().id};}
   else throw new Fault('Not found',404);
   tagPlans(next,previous,actor);await save(next,id);return result;
  });return json(200,result);
 }catch(e){if(!(e instanceof Fault))console.error(e);json(e.status||500,{error:e instanceof Fault?e.message:'Internal server error'});}
});
server.requestTimeout=15000;server.headersTimeout=10000;server.keepAliveTimeout=5000;
const port = Number(process.env.PORT || 8080);
const bindHost = process.env.HOST || (isCloud ? '0.0.0.0' : '127.0.0.1');
if (!process.env.VERCEL) {
  server.listen(port, bindHost, () => console.log('AtlasPay server: http://' + (bindHost === '0.0.0.0' ? 'localhost' : bindHost) + ':' + server.address().port));
}
export default server;
export { server, isCloud };
