import test from 'node:test';import assert from 'node:assert/strict';import { initialState,quote,pay } from './engine.mjs';import { invoice } from './business.mjs';import { approve,tagPlans,duplicates,invoiceNumber,search,forecast,template,runTemplate,accounting,backup,previewBackup } from './workflows.mjs';import { newKeys } from './pqc.mjs';
function plan(state=initialState()){const before=new Set(state.payments.map(p=>p.id)),q=quote(state,{sourceCurrency:'USD',targetCurrency:'EUR',amountMinor:'10000',recipient:'Vendor',purpose:'Invoice 123'}),p=pay(state,{quoteId:q.id,mode:'external',providerName:'Wise',providerUrl:'https://wise.com/'},'workflows-'+crypto.randomUUID());tagPlans(state,before,'maker');return {state,p};}
test('approval requires another identity and correct server role',()=>{const {state,p}=plan();approve(state,{id:p.id,decision:'request'},'maker','preparer');assert.throws(()=>approve(state,{id:p.id,decision:'approve'},'maker','owner'),/different team/);assert.throws(()=>approve(state,{id:p.id,decision:'approve'},'reviewer','preparer'),/approver role/);assert.equal(approve(state,{id:p.id,decision:'approve'},'reviewer','approver').status,'approved');invoiceNumber(state,{id:p.id,number:'INV-123'});assert.equal(p.approval.status,'draft');});
test('approval fingerprint prevents approving edited quote',()=>{const {state,p}=plan();approve(state,{id:p.id,decision:'request'},'maker','owner');p.quote.amountMinor='20000';assert.throws(()=>approve(state,{id:p.id,decision:'approve'},'reviewer','approver'),/changed/);});
test('duplicate detector compares numbers, files and plan fields',()=>{const {state,p}=plan(),other=plan(state).p;invoiceNumber(state,{id:p.id,number:'INV-123'});invoiceNumber(state,{id:other.id,number:'inv-123'});const content=Buffer.from('Invoice 123').toString('base64');for(const id of [p.id,other.id])invoice(state,{paymentId:id,name:'invoice.txt',content});assert.deepEqual(new Set(duplicates(state).map(d=>d.kind)),new Set(['Invoice number','Identical invoice file','Repeated payment plan']));});
test('search finds invoice, reference, attachment and batch, filters dates and status',()=>{const {state,p}=plan();p.invoiceNumber='INV-123';p.external.reference='BANK-456';state.batches=[{name:'October payroll',paymentIds:[p.id]}];state.invoices=[{name:'supplier-invoice.pdf',paymentId:p.id}];for(const term of ['inv-123','bank-456','payroll','supplier-invoice'])assert.equal(search(state,{term}).length,1);assert.equal(search(state,{status:'completed'}).length,0);assert.equal(search(state,{from:'2099-01-01'}).length,0);});
test('forecast sums currencies using actual fee, excludes sent and dates beyond horizon',()=>{const {state,p}=plan();p.actualCost={feeMinor:'150'};p.reminder={dueAt:'2026-10-07T00:00:00Z'};const other=plan(state).p;other.status='external_sent';const f=forecast(state,{days:7},Date.parse('2026-10-06T00:00:00Z'));assert.equal(f.rows.length,1);assert.equal(f.currencies.find(c=>c.currency==='USD').plannedMinor,'10150');});
test('monthly template clamps end of month and rerun of the same period is idempotent',()=>{const s=initialState(),t=template(s,{name:'Monthly invoice',cadence:'monthly',nextDate:'2027-01-31',recipient:'Vendor',purpose:'Monthly service',amount:'100',sourceCurrency:'USD',targetCurrency:'EUR',providerName:'Wise',providerUrl:'https://wise.com/'});const p=runTemplate(s,{id:t.id,date:'2027-01-31'});assert.equal(t.nextDate,'2027-02-28');assert.equal(runTemplate(s,{id:t.id,date:'2027-01-31'}).id,p.id);assert.equal(s.payments.length,1);assert.equal(s.journals.length,0);});
test('accounting distinguishes unverified plans and neutralizes formulas',()=>{const {state,p}=plan();p.quote.recipient='=HYPERLINK("bad")';const csv=accounting(state).csv;assert.match(csv,/Unverified external plan/);assert.ok(csv.includes("'=HYPERLINK"));assert.match(csv,/Amount minor/);});
test('backup verifies signatures and scope; ciphertext modifications fail',()=>{const {state}=plan(),k=newKeys(),archive=backup(state,'workspace-A',k);assert.deepEqual(previewBackup(archive,'workspace-A',[k]).state,state);assert.throws(()=>previewBackup(archive,'workspace-B',[k]),/another workspace/);const changed=structuredClone(archive);changed.envelope.ciphertext=changed.envelope.ciphertext.slice(0,-4)+'AAAA';assert.throws(()=>previewBackup(changed,'workspace-A',[k]),/verification failed/);});
