const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {installAccountSecurity} from './account-security.js';
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(n)/10**(c==='JPY'?0:2));
const major=(n,c)=>(Number(n)/10**(c==='JPY'?0:2)).toFixed(c==='JPY'?0:2);
let selectedOperation,identityWorkspace;
function toMinor(value,c){if(!/^\d+(?:\.\d{1,2})?$/.test(value)||(c==='JPY'&&value.includes('.')))throw Error('Enter a valid currency amount');const d=c==='JPY'?0:2,[a,b='']=value.split('.');return (BigInt(a)*10n**BigInt(d)+BigInt((b+'00').slice(0,d)||'0')).toString();}
const options=(ps,selected)=>ps.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.quote.recipient)} · ${money(p.quote.amountMinor,p.quote.sourceCurrency)} · ${esc(p.external.provider.name)}</option>`).join('');
export const businessTitles={operations:'Keep every payment ready.',batches:'Plan your next payment run.',accounts:'A workspace for your business.',integrations:'Verify status at the source.'};
export function identity(state){if(identityWorkspace!==state.workspace.id)selectedOperation=null;identityWorkspace=state.workspace.id;const el=$('.workspace');if(el)el.innerHTML=`${esc(state.workspace.name)}<small>${state.workspace.id==='demo'?'Shared local demo':'Signed-in customer sandbox'}</small>`;const bottom=$('.bottom');if(bottom)bottom.innerHTML=`● ${state.workspace.id==='demo'?'Demo':'Customer'} workspace<p id="reminder-count">${state.reminders?.length||0} overdue payment reminders</p><hr>${esc(state.workspace.email||'Local demo operator')}`;}
export function refreshReminders(state){if($('#reminder-count'))$('#reminder-count').textContent=(state.reminders?.length||0)+' overdue payment reminders';}
export function installBusiness(){const accountButton=document.createElement('button');accountButton.className='link';accountButton.dataset.view='accounts';accountButton.textContent='Sign up / Sign in';document.querySelector('header').append(accountButton);for(const [view,label] of [['operations','☑ Payment operations'],['batches','▤ Batch planning'],['accounts','♙ Sign up / Sign in'],['integrations','⇌ Provider connections']]){const b=document.createElement('button');b.dataset.view=view;b.textContent=label;$('nav').append(b);}}
export function renderBusiness(view,state,post,load,toast){
 const content=$('#content'),ps=state.payments.filter(p=>p.mode==='external');
 const run=(form,action)=>{form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');if(button.disabled)return;button.disabled=true;const controls=[...form.querySelectorAll('input,select,textarea,button')];try{const pending=action(form);controls.forEach(i=>i.disabled=true);await pending;await load();toast('Saved to your workspace');}catch(err){toast(err.message);}finally{controls.forEach(i=>i.disabled=false);}};};
 if(view==='accounts'){
  content.innerHTML=`<div class="panel"><h2>${state.workspace.id==='demo'?'You are using the shared local demo':esc(state.workspace.name)}</h2><p>${state.workspace.id==='demo'?'Create a customer workspace to keep payments, invoices, recipients and batches separate.':'Signed in as '+esc(state.workspace.email)}</p><p>Local sandbox accounts · Passwords are hashed · Sessions expire after 8 hours · Email verification and authenticator MFA are available below. Mobile SMS verification is not connected.</p>${state.workspace.id!=='demo'?'<button id="logout" class="primary">Sign out to demo workspace</button>':''}</div><div class="feature-grid feature-space"><div class="panel"><h2>Sign up</h2><form id="register"><label>Business name<input name="name" minlength="2" maxlength="80" required autocomplete="organization"></label><label>Email ID<input name="email" type="email" required autocomplete="email"></label><label>Mobile number with country code<input name="mobile" type="tel" required maxlength="30" placeholder="+919876543210" autocomplete="tel"></label><label>Password (at least 12 characters)<input name="password" type="password" minlength="12" maxlength="128" required autocomplete="new-password"></label><button class="primary wide">Sign up</button></form></div><div class="panel"><h2>Sign in</h2><form id="login"><label>Email ID<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" maxlength="128" required autocomplete="current-password"></label><button class="primary wide">Sign in</button></form></div></div>`;
  for(const name of ['register','login'])run($('#'+name),async f=>{await post('accounts/'+name,Object.fromEntries(new FormData(f)));});if($('#logout'))$('#logout').onclick=async()=>{try{await post('accounts/logout',{});await load();toast('Signed out');}catch(e){toast(e.message);}};
  installAccountSecurity(post,load,toast);
  if(state.workspace.id!=='demo'){const profilePanel=document.createElement('div');profilePanel.className='panel feature-space';profilePanel.id='personal-profile';content.prepend(profilePanel);fetch('/api/profile').then(async r=>{if(!r.ok)throw Error('Profile unavailable');const p=await r.json();if(!p||!$('#personal-profile'))return;profilePanel.innerHTML=`<h2>Your account</h2><p>Email ID: ${esc(p.email)}<br>Mobile number: ${esc(p.mobile||'Not provided')}</p><form id="mobile-profile"><label>Update mobile number (country code required)<input name="mobile" type="tel" required maxlength="30" value="${esc(p.mobile||'')}" autocomplete="tel" placeholder="+919876543210"></label><button class="primary wide">Save mobile number</button></form><p>Email: ${p.emailVerified?'Verified by email token':esc(p.emailVerificationMode)} · MFA: ${p.mfaEnabled?'Enabled':'Disabled'}<br>Mobile ownership is unverified; no SMS is sent.</p>`;run($('#mobile-profile'),f=>post('accounts/profile',{mobile:f.elements.mobile.value}));}).catch(e=>toast(e.message));}
 }
 if(view==='operations'){
  const due=state.reminders||[];content.innerHTML=`<div class="panel"><h2>Payment reminders · ${due.length} overdue</h2>${due.map(r=>`<div class="audit"><b>${esc(r.recipient)}</b> · ${esc(r.provider)}<small>Due ${esc(new Date(r.dueAt).toLocaleString())}</small></div>`).join('')||'<p>No overdue reminders. Set a due date on a payment below.</p>'}<p>The sidebar reminder count refreshes every minute while AtlasPay is open. Reopen this page or refresh the list for current reminders. No email or external notification is sent.</p><button id="refresh-reminders" class="link">Refresh reminders</button></div><div class="panel feature-space"><h2>Manage an external payment</h2>${ps.length?`<label>Payment<select id="operation-payment">${options(ps,selectedOperation)}</select></label><div id="operation-detail"></div>`:'<div class="empty">Prepare an external payment or batch to start.</div>'}</div>`;
  $('#refresh-reminders').onclick=()=>load().catch(e=>toast(e.message));if(!ps.length)return;
  const detail=()=>{
   const p=ps.find(p=>p.id===$('#operation-payment').value),c=p.quote.sourceCurrency,t=p.quote.targetCurrency;
   $('#operation-detail').innerHTML=`<p>Status: <b>${esc(p.status.replaceAll('_',' '))}</b> · ${esc(p.external.confirmation)}</p><div class="feature-grid"><div><h2>Pre-payment checklist</h2><form id="checklist">${[['recipient','Recipient bank details checked'],['invoice','Invoice and payment purpose checked'],['amount','Amount checked against the provider quote'],['currency','Sending and receiving currencies checked']].map(([key,label])=>`<label class="check-row"><input type="checkbox" name="${key}" ${p.checklist?.[key]?'checked':''}>${label}</label>`).join('')}<button class="primary wide">Save checklist</button></form><p>Checklist records your checks; it does not verify bank details automatically.</p><h2>Reminder</h2><form id="reminder"><label>Remind me at<input type="datetime-local" name="due" required></label><button class="primary wide">Schedule / snooze reminder</button></form><p>${p.reminder?'Scheduled: '+esc(new Date(p.reminder.dueAt).toLocaleString()):'No reminder scheduled'}</p></div><div><h2>Actual provider cost</h2><form id="cost"><label>Actual fee (${c})<input name="fee" inputmode="decimal" required value="${p.actualCost?major(p.actualCost.feeMinor,c):''}"></label><label>Recipient actually receives (${t})<input name="received" inputmode="decimal" required value="${p.actualCost?major(p.actualCost.receiveMinor,t):''}"></label><button class="primary wide">Save actual cost</button></form>${p.actualCost?`<p>Fee difference: ${money(p.actualCost.feeDifferenceMinor,c)}<br>Recipient amount difference: ${money(p.actualCost.receiveDifferenceMinor,t)}<br>Effective FX rate: ${(Number(p.actualCost.receiveMinor)/10**(t==='JPY'?0:2)/(Number(p.quote.amountMinor)/10**(c==='JPY'?0:2))).toFixed(6)} ${t}/${c}<br>Self-reported figures; settlement remains unverified.</p>`:'<p>Compare your provider’s actual figures with the illustrative AtlasPay estimate.</p>'}<h2>Invoice attachments</h2><form id="invoice"><label>Invoice (PDF, PNG, JPEG or TXT · up to 500 KiB)<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.txt" required></label><button class="primary wide">Attach invoice</button></form>${(state.invoices||[]).filter(i=>i.paymentId===p.id).map(i=>`<p><a href="/api/invoices/${i.id}">${esc(i.name)} ↓</a> · ${Math.ceil(i.size/1024)} KiB<br><small>SHA-384 ${esc(i.sha384.slice(0,28))}…</small></p>`).join('')}</div></div>`;
   run($('#checklist'),f=>post('business/checklist',{id:p.id,checks:Object.fromEntries(['recipient','invoice','amount','currency'].map(k=>[k,f.elements[k].checked]))}));
   run($('#reminder'),f=>post('business/reminder',{id:p.id,dueAt:new Date(f.elements.due.value).toISOString()}));
   run($('#cost'),f=>post('business/cost',{id:p.id,feeMinor:toMinor(f.elements.fee.value,c),receiveMinor:toMinor(f.elements.received.value,t)}));
   run($('#invoice'),async f=>{const file=f.elements.file.files[0];if(!file||file.size>512000)throw Error('Choose a file up to 500 KiB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return post('business/invoice',{paymentId:p.id,name:file.name,content:btoa(binary)});});
  };$('#operation-payment').onchange=()=>{selectedOperation=$('#operation-payment').value;detail();};detail();
 }
 if(view==='batches'){
  content.innerHTML=`<div class="panel"><h2>Batch payment planning</h2><p>Prepare up to 50 supplier payments together. Each becomes an external plan; no money moves. Check each recipient and invoice in Payment operations before paying.</p><form id="batch"><div class="row"><label>Batch name<input name="name" required minlength="2" maxlength="80" placeholder="October supplier run"></label><label>Provider<select name="provider"><option value="wise">Wise</option><option value="paypal">PayPal</option><option value="remitly">Remitly</option></select></label></div><div class="table-wrap"><table><thead><tr><th>RECIPIENT</th><th>AMOUNT</th><th>FROM</th><th>TO</th><th>PURPOSE</th><th></th></tr></thead><tbody id="batch-rows"></tbody></table></div><div class="toolbar feature-space"><button type="button" id="add-row" class="link">+ Add recipient</button><button class="primary">Prepare batch</button></div></form></div><div class="panel feature-space"><h2>Saved batches</h2>${(state.batches||[]).map(b=>`<div class="audit"><b>${esc(b.name)}</b> · ${b.paymentIds.length} external plans<small>${esc(new Date(b.createdAt).toLocaleString())}</small></div>`).join('')||'<p>No batches yet.</p>'}</div>`;
  let key=crypto.randomUUID();const add=()=>{if($('#batch-rows').children.length>=50)return;const row=document.createElement('tr');row.innerHTML=`<td><input name="recipient" required minlength="2" placeholder="Supplier"></td><td><input name="amount" required inputmode="decimal" placeholder="100.00"></td>${['sourceCurrency','targetCurrency'].map((k,i)=>`<td><select name="${k}">${Object.keys(state.wallets).map(c=>`<option ${c===(i?'EUR':'USD')?'selected':''}>${c}</option>`).join('')}</select></td>`).join('')}<td><input name="purpose" required minlength="3" placeholder="Invoice number"></td><td><button type="button" class="link" aria-label="Remove row">✕</button></td>`;row.querySelector('button').onclick=()=>{row.remove();key=crypto.randomUUID();};$('#batch-rows').append(row);};$('#add-row').onclick=add;add();$('#batch').addEventListener('input',()=>key=crypto.randomUUID());$('#batch').addEventListener('change',()=>key=crypto.randomUUID());
  run($('#batch'),async f=>{const providers={wise:['Wise','https://wise.com/'],paypal:['PayPal','https://www.paypal.com/'],remitly:['Remitly','https://www.remitly.com/']},[providerName,providerUrl]=providers[f.elements.provider.value];const rows=[...$('#batch-rows').children].map(tr=>Object.fromEntries([...tr.querySelectorAll('input,select')].map(i=>[i.name,i.value])));await post('business/batch',{name:f.elements.name.value,providerName,providerUrl,rows},key);});
 }
 if(view==='integrations'){
  content.innerHTML=`<div class="panel"><h2>Wise status connection</h2><p id="connection-status">Checking server configuration…</p><p>This read-only connector checks an existing Wise transfer. It never sends money or creates a transfer. A sandbox API response remains test evidence. A live “sent” status does not guarantee recipient delivery.</p><p>Workspace ID: <code>${esc(state.workspace.id)}</code></p><p>Credentials must be configured on the server for this workspace. Do not enter API tokens into payment references or website fields.</p></div><div class="panel feature-space"><h2>Check a provider transfer</h2><form id="provider-check"><label>Wise payment plan<select name="id">${options(ps.filter(p=>p.external.provider.name==='Wise'))}</select></label><div class="row"><label>Wise transfer ID<input name="transferId" pattern="[0-9]{1,16}" required></label><label>Wise recipient account ID<input name="recipientId" pattern="[0-9]{1,16}" required></label></div><button class="primary wide">Check provider status</button></form><p>The connector checks your configured business profile, recipient ID, currencies and source amount before recording a response.</p>${ps.filter(p=>p.providerConfirmation).map(p=>`<div class="audit">${esc(p.quote.recipient)} · ${esc(p.providerConfirmation.environment)} · ${esc(p.providerConfirmation.status)}<small>Checked ${esc(new Date(p.providerConfirmation.checkedAt).toLocaleString())}</small></div>`).join('')}</div>`;
  fetch('/api/integrations').then(async r=>{const c=await r.json();if(!r.ok)throw Error(c.error);if($('#connection-status'))$('#connection-status').textContent=c.configured?'Configured · '+c.environment+' · Read-only':'Not connected. Provider credentials are required.';}).catch(e=>toast(e.message));run($('#provider-check'),f=>post('provider/check',Object.fromEntries(new FormData(f))));
 }
}
