const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(n)/10**(c==='JPY'?0:2));
export const providers=[{id:'wise',name:'Wise',url:'https://wise.com/'},{id:'paypal',name:'PayPal',url:'https://www.paypal.com/'},{id:'remitly',name:'Remitly',url:'https://www.remitly.com/'}];
let selectedProvider='wise';
export function renderProviders(){
 document.querySelector('#content').innerHTML=`<div class="panel"><h2>Choose a payment provider</h2><p>These links open official provider websites. They are not connected integrations. Check your provider’s country, currency and business-payment eligibility before sending.</p><div class="provider-grid">${providers.map(p=>`<div class="wallet"><h2>${p.name}</h2><p>${new URL(p.url).hostname}</p><p><a href="${p.url}" target="_blank" rel="noopener noreferrer">Open official website ↗</a></p><button class="primary" data-plan-provider="${p.id}">Plan payment with ${p.name}</button></div>`).join('')}<div class="wallet"><h2>Your bank or another app</h2><p>Use a provider you already trust and enter its official website.</p><button class="primary" data-plan-provider="custom">Plan with another provider</button></div></div><p>Choose a provider → enter payment details → get an estimate → Pay through provider. You confirm the actual transfer in the provider’s own app.</p></div>`;
 document.querySelectorAll('[data-plan-provider]').forEach(b=>b.onclick=()=>{selectedProvider=b.dataset.planProvider;document.querySelector('#new').click();});
}
export function installHandoff(getQuote,post,load,toast){
 const button=document.createElement('button');button.id='pay-provider';button.type='button';button.className='primary wide';button.textContent='Pay through provider ↗';button.hidden=true;document.querySelector('#confirm').after(button);
 new MutationObserver(()=>{button.hidden=document.querySelector('#confirm').hidden;}).observe(document.querySelector('#confirm'),{attributes:true,attributeFilter:['hidden']});
 const dialog=document.createElement('dialog');dialog.id='provider-dialog';dialog.innerHTML=`<div class="intro"><h2>Pay through provider</h2><button type="button" id="provider-close" aria-label="Close">✕</button></div><p>AtlasPay prepares a payment plan. You must enter and confirm the real payment in your bank or authorized payment app. No payment details are sent automatically.</p><div id="provider-plan"></div><form id="provider-form"><label>Payment app or bank name<input name="providerName" required minlength="2" maxlength="80" placeholder="Your authorized payment provider"></label><label>Official provider website<input name="providerUrl" type="url" required maxlength="500" placeholder="https://your-provider.com/"></label><p>Use the official website you trust. AtlasPay does not verify this provider’s authorization or availability in your country. Your provider supplies the actual fees and FX rate.</p><p id="provider-error" role="alert"></p><button class="primary wide">Prepare external payment</button></form><div id="provider-ready" hidden></div>`;document.body.append(dialog);
 let q,k,body;
 button.onclick=()=>{q=getQuote();if(!q)return;k=crypto.randomUUID();body=null;document.querySelector('#dialog').close();document.querySelector('#provider-form').hidden=false;document.querySelector('#provider-ready').hidden=true;document.querySelector('#provider-error').textContent='';document.querySelector('#provider-plan').innerHTML=`<div class="quote-box"><div><span>Recipient</span><b>${esc(q.recipient)}</b></div><div><span>Send amount</span><b>${money(q.amountMinor,q.sourceCurrency)}</b></div><div><span>Illustrative recipient amount</span><b>${money(q.receiveMinor,q.targetCurrency)}</b></div><p>${esc(q.purpose)} · Estimate only. Provider quote takes precedence.</p></div>`;dialog.showModal();};
 document.querySelector('#provider-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target.closest('[data-view]'))dialog.close();});
 const form=document.querySelector('#provider-form');const pickerLabel=document.createElement('label');pickerLabel.innerHTML=`Choose a provider<select id="provider-picker">${providers.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}<option value="custom">My bank / another provider</option></select>`;form.prepend(pickerLabel);
 const picker=document.querySelector('#provider-picker');
 const checks=document.createElement('div');checks.innerHTML=`<h2>Before you continue</h2>${[['recipient','Recipient banking details checked'],['invoice','Invoice and purpose checked'],['amount','Amount checked'],['currency','Currencies checked']].map(([k,label])=>`<label class="check-row"><input type="checkbox" name="check_${k}" required>${label}</label>`).join('')}`;form.querySelector('button').before(checks);
 function chooseProvider(){const p=providers.find(p=>p.id===picker.value);selectedProvider=picker.value;form.elements.providerName.readOnly=!!p;form.elements.providerUrl.readOnly=!!p;form.elements.providerName.value=p?.name||'';form.elements.providerUrl.value=p?.url||'';k=crypto.randomUUID();body=null;}
 picker.onchange=chooseProvider;
 button.addEventListener('click',()=>{picker.value=selectedProvider;chooseProvider();});
 chooseProvider();
 form.addEventListener('input',()=>{k=crypto.randomUUID();body=null;});
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;form.querySelectorAll('input').forEach(i=>i.disabled=true);try{body??={quoteId:q.id,mode:'external',providerName:form.elements.providerName.value,providerUrl:form.elements.providerUrl.value,checks:Object.fromEntries(['recipient','invoice','amount','currency'].map(k=>[k,form.elements['check_'+k].checked]))};const p=await post('payments',body,k);await load();form.hidden=true;document.querySelector('#provider-ready').hidden=false;document.querySelector('#provider-ready').innerHTML=`<h2>Awaiting external payment</h2><p>Your handoff is saved. Open your provider and enter the payment details there. AtlasPay has not moved any funds.</p><p>${p.approval?.status==='approved'?`<a class="primary provider-link" href="${esc(p.external.provider.url)}" target="_blank" rel="noopener noreferrer">Open ${esc(p.external.provider.name)} ↗</a>`:`<button class="primary" data-view="team">Submit for team approval →</button>`}</p><p>After paying, use External payments to record the provider reference. A reference alone does not confirm settlement.</p>`;toast('Awaiting external payment');}catch(err){document.querySelector('#provider-error').textContent=err.message;}finally{b.disabled=false;form.querySelectorAll('input').forEach(i=>i.disabled=false);}};
}
export function renderExternal(state,post,load,toast){
 const ps=state.payments.filter(p=>p.mode==='external');
 document.querySelector('#content').innerHTML=`<div class="panel"><h2>External payment plans · ${ps.length}</h2><p>These are payment plans, not completed transfers. Demo wallets are untouched. Complete each payment in your authorized provider’s app, using its actual quote and verified recipient details.</p>${ps.map(p=>`<div class="audit"><p>${p.archivedAt?'Archived � ':''}${p.status==='plan_cancelled'?'Cancelled plan � ':''}</p><div class="recipient-row"><div><b>${esc(p.quote.recipient)} · ${money(p.quote.amountMinor,p.quote.sourceCurrency)}</b><small>${esc(p.quote.purpose)} · ${esc(p.external.provider.name)} · ${esc(p.id)}</small></div><span class="badge review">${p.status==='plan_cancelled'?'Plan cancelled locally':p.status==='awaiting_external_payment'?'Awaiting external payment':p.status==='external_sent'?'Provider reports sent':'Provider reports failed'}</span></div><p>${!p.archivedAt&&p.status==='awaiting_external_payment'&&p.approval?.status==='approved'&&['recipient','invoice','amount','currency'].every(k=>p.checklist?.[k])?`<a href="${esc(p.external.provider.url)}" target="_blank" rel="noopener noreferrer">Open ${esc(p.external.provider.name)} ↗</a>`:`<button class="link" data-view="operations">Complete checklist / team approval →</button>`}</p><button class="link" data-view="operations">Manage invoice, reminder and actual costs →</button><p><button class="link" data-plan="${p.id}" data-action="${p.archivedAt?'unarchive':'archive'}">${p.archivedAt?'Unarchive':'Archive'} plan</button> ${p.status==='awaiting_external_payment'&&!p.external.reference&&!p.providerConfirmation?`<button class="link" data-plan="${p.id}" data-action="cancel">Cancel local plan</button>`:''}</p><form data-reference="${p.id}"><label>Provider reference (self-reported)<input name="reference" value="${esc(p.external.reference||'')}" minlength="3" maxlength="120" required placeholder="Reference from your provider"></label><button class="link wide">Save reference</button></form><p>${esc(p.external.confirmation)}. ${p.providerConfirmation?`Status checked via Wise ${esc(p.providerConfirmation.environment)} API. Recipient delivery is not confirmed.`:'No provider API response has been verified for this plan.'}</p></div>`).join('')||'<div class="empty">Create a quote, then choose Pay through provider.</div>'}</div>`;
 document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await post('external/lifecycle',{id:b.dataset.plan,action:b.dataset.action});await load();toast('Local plan updated. Provider payments are unchanged.');}catch(err){toast(err.message);b.disabled=false;}});
 document.querySelectorAll('[data-reference]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{await post('external/reference',{id:f.dataset.reference,reference:f.elements.reference.value});await load();toast('Reference saved; awaiting provider confirmation');}catch(err){toast(err.message);b.disabled=false;}});
}
