import { renderExternal, renderProviders } from './external.js';
import { renderBusiness, installBusiness, businessTitles } from './business.js';
import { renderWorkflows,installWorkflows,workflowTitles } from './workflows.js';
import { installReadiness,renderReadiness } from './readiness.js';
import { renderPricing, pricingTitles } from './pricing.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const featureTitles={readiness:'Your next step, made clear.',pricing:'Transparent pricing for global businesses.',...workflowTitles,...businessTitles,providers:'Choose where to send your money.',external:'Continue with your payment provider.',security:'Security you can inspect.',beneficiaries:'Your global recipient network.',reconciliation:'Close the loop on every payment.'};
export function installFeatures(){
 installReadiness();
 installBusiness();
 installWorkflows();
  const nav=document.querySelector('nav');for(const [view,label] of [['pricing','⊞ Pricing & Add-ons'],['providers','▦ Payment providers'],['external','↗ External payments'],['beneficiaries','♧ Recipients'],['reconciliation','⇄ Reconciliation'],['security','⬡ PQC security']]){const b=document.createElement('button');b.dataset.view=view;b.textContent=label;nav.append(b);}
}
function download(body,name){const url=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function renderFeature(view,state,post,load,toast){
 const content=document.querySelector('#content');
 if(view==='readiness')return renderReadiness(toast);
 if(view==='pricing')return renderPricing(state,toast);
 if(Object.hasOwn(workflowTitles,view))return renderWorkflows(view,state,post,load,toast).catch(e=>toast(e.message));
 if(Object.hasOwn(businessTitles,view))return renderBusiness(view,state,post,load,toast);
 if(view==='providers')return renderProviders();
 if(view==='external')return renderExternal(state,post,load,toast);
 if(view==='beneficiaries'){
  content.innerHTML=`<div class="feature-grid"><div class="panel"><h2>Save a recipient</h2><p>Keep payout details ready for your next transfer. This address book does not verify recipient identity.</p><form id="beneficiary-form"><label>Company or recipient<input name="name" required minlength="2" maxlength="100"></label><div class="row"><label>Country code<input name="country" placeholder="IN" pattern="[A-Za-z]{2}" maxlength="2" required></label><label>Preferred currency<select name="currency">${Object.keys(state.wallets).map(c=>`<option>${c}</option>`).join('')}</select></label></div><button class="primary wide">Save recipient</button><p id="beneficiary-error" role="alert"></p></form></div><div class="panel"><h2>Recipient directory</h2>${(state.beneficiaries||[]).map(b=>`<div class="audit recipient-row"><div><b>${escape(b.name)}</b><small>${escape(b.country)} · ${b.currency} · Sandbox address book</small></div><button class="link" data-recipient="${b.id}">Pay ↗</button></div>`).join('')||'<div class="empty">Save your first recipient to simplify repeat payments.</div>'}</div></div>`;
  document.querySelector('#beneficiary-form').onsubmit=async e=>{e.preventDefault();const f=e.target.elements,b=e.target.querySelector('button');b.disabled=true;try{await post('beneficiaries',{name:f.name.value,country:f.country.value.toUpperCase(),currency:f.currency.value});await load();toast('Recipient saved');}catch(err){document.querySelector('#beneficiary-error').textContent=err.message;b.disabled=false;}};
  content.querySelectorAll('[data-recipient]').forEach(b=>b.onclick=()=>{const recipient=state.beneficiaries.find(r=>r.id===b.dataset.recipient),f=document.querySelector('#form');f.elements.recipient.value=recipient.name;f.elements.targetCurrency.value=recipient.currency;f.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#dialog').showModal();});
 }
 if(view==='reconciliation'){
  const report=state.reconciliation;
  content.innerHTML=`<div class="panel"><h2>Statement matching</h2><p>Compare external statement rows against completed sandbox transfers. Amounts must be source-currency minor units including fees. The report flags missing, duplicate, unexpected and mismatched records.</p><form id="reconcile-form"><label>Statement JSON<textarea name="rows" id="statement" rows="8" required spellcheck="false" aria-label="Statement rows"></textarea></label><div class="toolbar"><button class="primary">Run reconciliation</button><button type="button" id="template" class="link">Use current payments as a sample</button></div><p id="reconcile-error" role="alert"></p></form></div><div class="panel feature-space"><h2>Latest reconciliation</h2>${report?`<p>${escape(new Date(report.at).toLocaleString())} · ${Object.entries(report.counts).map(([s,n])=>`${escape(s)}: ${n}`).join(' · ')}</p><div class="table-wrap"><table><thead><tr><th>REFERENCE</th><th>CURRENCY</th><th>AMOUNT MINOR</th><th>RESULT</th></tr></thead><tbody>${report.results.map(r=>`<tr><td>${escape(r.reference)}</td><td>${escape(r.currency)}</td><td>${escape(r.amountMinor)}</td><td><span class="badge ${r.status==='matched'?'':r.status==='mismatch'?'rejected':'review'}">${r.status}</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Run a statement to view discrepancies.</div>'}</div>`;
  const sample=()=>JSON.stringify(state.payments.filter(p=>p.status==='completed').map(p=>({reference:p.id,currency:p.quote.sourceCurrency,amountMinor:p.quote.totalMinor})),null,2);
  document.querySelector('#statement').value=sample();document.querySelector('#template').onclick=()=>document.querySelector('#statement').value=sample();
  document.querySelector('#reconcile-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const rows=JSON.parse(e.target.elements.rows.value);await post('reconcile',{rows});await load();toast('Statement reconciled');}catch(err){document.querySelector('#reconcile-error').textContent=err.message;b.disabled=false;}};
 }
 if(view==='security'){
  content.innerHTML=`<div class="metrics"><div class="metric"><label>Receipt signatures</label><strong class="crypto-label">ML-DSA-65</strong><small>Plus Ed25519 · both signatures required</small></div><div class="metric"><label>Encrypted exports</label><strong class="crypto-label">ML-KEM-768</strong><small>HKDF-SHA384 · AES-256-GCM</small></div><div class="metric"><label>Security boundary</label><strong class="crypto-label">Local sandbox</strong><small>No HSM, production identity or PQC TLS</small></div></div><div class="panel feature-space"><h2>PQC control center</h2><p>Payment receipts are signed at settlement. Encrypted exports protect the downloaded archive. Operational state and the private keyring remain local plaintext files.</p><div class="toolbar"><button class="primary" id="self-test">Run crypto self-test</button><button class="link" id="verify-receipts">Verify receipts</button><button class="link" id="secure-export">Download encrypted archive ↓</button><button class="link" id="rotate-keys">Rotate PQC keys</button></div><p id="security-result" role="status"></p><div id="security-details">Loading key inventory…</div></div><div class="panel feature-space"><h2>Receipt inventory</h2><div id="receipts"></div></div>`;
  const details=async()=>{const r=await fetch('/api/security');if(!r.ok)throw Error('Security inventory unavailable');const s=await r.json();if(!document.querySelector('#security-details'))return;document.querySelector('#security-details').innerHTML=`<div class="table-wrap"><table><thead><tr><th>KEY ID</th><th>CREATED</th><th>STATE</th></tr></thead><tbody>${s.keys.map(k=>`<tr><td>${escape(k.id)}<small>SHA-384 fingerprint ${escape(k.fingerprint.slice(0,32))}…</small></td><td>${escape(new Date(k.createdAt).toLocaleString())}</td><td><span class="badge">${k.id===s.activeKeyId?'Active':'Retained'}</span></td></tr>`).join('')}</tbody></table></div><p>Runtime ${escape(s.runtime)} · ${escape(s.transport)}<br>${escape(s.keyStorage)} · ${escape(s.stateStorage)}</p>`;
  document.querySelector('#receipts').innerHTML=s.receipts.length?`<div class="table-wrap"><table><thead><tr><th>RECIPIENT / PAYMENT</th><th>INTEGRITY</th><th>RECEIPT</th></tr></thead><tbody>${s.receipts.map(r=>`<tr><td>${escape(r.recipient)}<small>${escape(r.id)}</small></td><td><span class="badge ${r.valid?'':'rejected'}">${r.valid?'Both signatures verified':'Verification failed'}</span></td><td><button class="link" data-receipt="${r.id}">Download ↓</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Complete a sandbox payment to create a signed receipt.</div>';
  document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>{const p=state.payments.find(p=>p.id===b.dataset.receipt);download({receipt:p.receipt,publicKey:s.keys.find(k=>k.id===p.receipt.keyId)},p.id+'-receipt.json');});
  };
  details().catch(e=>toast(e.message));
  for(const [id,path] of [['self-test','self-test'],['verify-receipts','verify'],['secure-export','export'],['rotate-keys','rotate']])document.querySelector('#'+id).onclick=async e=>{const b=e.target;b.disabled=true;try{const result=await post('security/'+path,{});if(path==='export'){download(result,'atlaspay-pqc-archive.json');toast('Encrypted archive downloaded. Retain your private keyring to decrypt it.');}else if(path==='self-test')document.querySelector('#security-result').textContent=`ML-KEM round trip: ${result.kemRoundTrip?'PASS':'FAIL'} · Dual signatures: ${result.dualSignature?'PASS':'FAIL'}`;else if(path==='verify'){await details();document.querySelector('#security-result').textContent='Receipt signatures and current payment/journal contents checked.';}else{await load();toast('New PQC keys active. Older keys retained for existing receipts and archives.');}}catch(err){toast(err.message);}finally{b.disabled=false;}};
 }
}
