const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(n)/10**(c==='JPY'?0:2));
export const workflowTitles={team:'Prepare together. Approve independently.',duplicates:'Catch repeated invoices early.',templates:'Reuse the work. Review every payment.',forecast:'Plan your currency needs.',history:'Find every payment detail.',recovery:'Recover with verified evidence.',accounting:'Records ready for bookkeeping.'};
export function installWorkflows(){for(const [view,label] of [['team','♧ Team & approvals'],['duplicates','⚑ Duplicate checks'],['templates','↻ Recurring templates'],['forecast','▥ Cash-flow forecast'],['history','⌕ Payment history'],['accounting','≡ Accounting exports'],['recovery','▣ Backup & recovery']]){const b=document.createElement('button');b.dataset.view=view;b.textContent=label;$('nav').append(b);}}
function download(value,name,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export async function renderWorkflows(view,state,post,load,toast){const content=$('#content');content.dataset.workflow=view;const current=()=>content.dataset.workflow===view&&document.querySelector('nav button.active')?.dataset.view===view;const attempt=fn=>async e=>{e?.preventDefault();const b=e?.currentTarget?.querySelector?.('button')||e?.currentTarget;if(b?.disabled)return;if(b)b.disabled=true;try{await fn(e);}catch(err){toast(err.message);}finally{if(b)b.disabled=false;}};
 if(view==='team'){
 const r=await fetch('/api/workflows'),info=await r.json();if(!r.ok)throw Error(info.error);if(!current())return;
 content.innerHTML=`<div class="panel"><h2>Team access · ${esc(info.role)}</h2><p>Assign another registered customer account a preparer, approver or read-only role. Owners and approvers can decide; nobody can approve a plan they prepared or submitted.</p><form id="switch"><label>Workspace<select name="workspaceId">${info.workspaces.map(w=>`<option value="${w.id}" ${w.id===state.workspace.id?'selected':''}>${esc(w.name)} · ${w.role}</option>`).join('')}</select></label><button class="primary wide">Switch workspace</button></form>${info.role==='owner'&&state.workspace.id!=='demo'?`<form id="member"><label>Registered teammate email<input name="email" type="email" required></label><label>Role<select name="role"><option>preparer</option><option>approver</option><option>viewer</option></select></label><button class="primary wide">Add / update teammate</button></form>`:'<p>Use a customer workspace to add teammates. Access decisions are enforced by the server.</p>'}${info.members.map(m=>`<p>${esc(m.email)} · ${m.role}</p>`).join('')}</div><div class="panel feature-space"><h2>External plan approvals</h2>${state.payments.filter(p=>p.mode==='external').map(p=>`<div class="audit"><b>${esc(p.quote.recipient)}</b> · ${money(p.quote.amountMinor,p.quote.sourceCurrency)} · ${esc(p.approval?.status||'draft')}<div class="toolbar"><button class="link" data-approval="request" data-id="${p.id}">Submit for approval</button>${p.approval?.status==='pending'?`<button class="link" data-approval="approve" data-id="${p.id}">Approve</button><button class="link" data-approval="reject" data-id="${p.id}">Reject</button>`:''}</div></div>`).join('')||'<p>No external plans.</p>'}</div>`;
 $('#switch').onsubmit=attempt(async e=>{await post('accounts/switch',Object.fromEntries(new FormData(e.target)));await load();});if($('#member'))$('#member').onsubmit=attempt(async e=>{await post('team/member',Object.fromEntries(new FormData(e.target)));await load();});document.querySelectorAll('[data-approval]').forEach(b=>b.onclick=attempt(async()=>{await post('approval',{id:b.dataset.id,decision:b.dataset.approval});await load();}));
 }
 if(view==='duplicates'){
 const info=await (await fetch('/api/workflows')).json();if(!current())return;content.innerHTML=`<div class="panel"><h2>Duplicate warnings · ${info.duplicates.length}</h2><p>Checks compare invoice numbers within a recipient, identical uploaded file hashes, and matching payment plan details. These are warnings for investigation, not proof of fraud.</p>${info.duplicates.map(d=>`<div class="audit"><b>${esc(d.kind)}</b><small>${esc(d.first)} ↔ ${esc(d.second)}</small></div>`).join('')||'<p>No duplicate warnings.</p>'}</div><div class="panel feature-space"><h2>Record an invoice number</h2><form id="invoice-number"><label>External plan<select name="id">${state.payments.filter(p=>p.mode==='external').map(p=>`<option value="${p.id}">${esc(p.quote.recipient)} · ${esc(p.quote.purpose)}</option>`).join('')}</select></label><label>Invoice number<input name="number" required maxlength="80"></label><button class="primary wide">Save and check duplicates</button></form><p>Changing an invoice number resets an existing approval.</p></div>`;$('#invoice-number').onsubmit=attempt(async e=>{await post('invoice-number',Object.fromEntries(new FormData(e.target)));await load();});
 }
 if(view==='accounting'){content.innerHTML=`<div class="panel"><h2>Export payment records</h2><p>Download a CSV with invoice numbers, currencies, integer amounts, estimated and actual fees, provider references, statuses and evidence labels. External plans remain separate from verified provider statuses and simulated settlements.</p><div class="toolbar"><button class="primary" id="accounting-export">Download payment records CSV ↓</button><button class="link" id="journal-export">Download sandbox journal CSV ↓</button></div></div>`;$('#accounting-export').onclick=attempt(async()=>{const result=await post('accounting/export',{});download(result.csv,result.filename,'text/csv');});$('#journal-export').onclick=attempt(async()=>{const result=await post('accounting/export',{kind:'journals'});download(result.csv,result.filename,'text/csv');});}
 if(view==='history'){
 content.innerHTML=`<div class="panel"><h2>Search payment history</h2><form id="history-search"><label>Recipient, invoice, filename, provider reference or batch<input name="term" placeholder="Search all payment details"></label><div class="row"><label>From date<input type="date" name="from"></label><label>Through date<input type="date" name="to"></label></div><label>Status<select name="status"><option value="all">All</option>${['awaiting_external_payment','external_sent','external_failed','completed','review','rejected'].map(s=>`<option>${s}</option>`).join('')}</select></label><button class="primary wide">Search</button></form><div id="history-results"></div></div>`;const show=ps=>$('#history-results').innerHTML=ps.map(p=>`<div class="audit"><b>${esc(p.quote.recipient)}</b> · ${money(p.quote.amountMinor,p.quote.sourceCurrency)} · ${esc(p.status)}<small>${esc(p.invoiceNumber||'No invoice number')} · ${esc(p.external?.reference||p.id)} · ${esc(new Date(p.at).toLocaleString())}</small></div>`).join('')||'<p>No matches.</p>';show(state.payments);$('#history-search').onsubmit=attempt(async e=>show(await post('search',Object.fromEntries(new FormData(e.target)))));
 }
 if(view==='forecast'){
 content.innerHTML=`<div class="panel"><h2>Upcoming currency needs</h2><p>Totals include awaiting external plans, using recorded actual fees where available. Undated plans and the next scheduled template occurrence are included. These are forecasts against demo balances, not connected bank balances.</p><label>Planning horizon<select id="forecast-days"><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option></select></label><div id="forecast-results"></div></div>`;const update=async()=>{const result=await post('forecast',{days:$('#forecast-days').value});if(!$('#forecast-results'))return;$('#forecast-results').innerHTML=`<div class="wallets feature-space">${result.currencies.map(c=>`<div class="wallet"><h2>${c.currency}</h2><p>Planned: ${money(c.plannedMinor,c.currency)}</p><p>Remaining demo funds: ${money(c.remainingDemoMinor,c.currency)}</p></div>`).join('')}</div><h2 class="feature-space">${result.rows.length} planned payments</h2>${result.rows.map(p=>`<div class="audit">${esc(p.recipient)} · ${money(p.amountMinor,p.currency)}<small>${p.dueAt?esc(new Date(p.dueAt).toLocaleDateString()):'Undated'} · ${esc(p.basis)}</small></div>`).join('')}`;};$('#forecast-days').onchange=()=>update().catch(e=>toast(e.message));await update();
 }
 if(view==='templates'){
 content.innerHTML=`<div class="feature-grid"><div class="panel"><h2>Save recurring payment details</h2><p>Templates create plans on demand. They never automatically send money.</p><form id="template"><label>Name<input name="name" required minlength="2"></label><label>Recipient<input name="recipient" required minlength="2"></label><label>Purpose<input name="purpose" required minlength="3"></label><label>Amount<input name="amount" required inputmode="decimal"></label><div class="row">${['sourceCurrency','targetCurrency'].map((k,i)=>`<label>${i?'Receive':'Send'} currency<select name="${k}">${Object.keys(state.wallets).map(c=>`<option ${c===(i?'EUR':'USD')?'selected':''}>${c}</option>`).join('')}</select></label>`).join('')}</div><label>Provider<select name="provider"><option>Wise</option><option>PayPal</option><option>Remitly</option></select></label><div class="row"><label>Frequency<select name="cadence"><option>monthly</option><option>weekly</option><option>manual</option></select></label><label>Next date<input type="date" name="nextDate" required></label></div><button class="primary wide">Save template</button></form></div><div class="panel"><h2>Saved templates</h2>${(state.templates||[]).map(t=>`<div class="audit"><b>${esc(t.name)}</b> · ${t.cadence}<small>Next ${t.nextDate} · ${esc(t.details.recipient)}</small><button class="link" data-template="${t.id}" data-date="${t.nextDate}">Create next payment plan</button></div>`).join('')||'<p>No templates yet.</p>'}</div></div>`;$('#template').onsubmit=attempt(async e=>{const f=Object.fromEntries(new FormData(e.target));const links={Wise:'https://wise.com/',PayPal:'https://www.paypal.com/',Remitly:'https://www.remitly.com/'};await post('templates/create',{...f,providerName:f.provider,providerUrl:links[f.provider]});await load();});document.querySelectorAll('[data-template]').forEach(b=>b.onclick=attempt(async()=>{await post('templates/run',{id:b.dataset.template,date:b.dataset.date});await load();}));
 }
 if(view==='recovery'){
 content.innerHTML=`<div class="panel"><h2>Encrypted workspace backup</h2><p>Includes invoices, templates, payment records and idempotency history. Does not include account passwords or private keys. Keep the original keyring separately; only this workspace can restore its backup.</p><button id="backup-export" class="primary">Download PQC backup ↓</button></div><div class="panel feature-space"><h2>Verify before recovery</h2><form id="backup-preview"><label>AtlasPay backup JSON<input type="file" name="archive" accept=".json" required></label><button class="primary wide">Verify and preview recovery</button></form><div id="backup-summary"></div></div>`;$('#backup-export').onclick=attempt(async()=>download(await post('backup/export',{}),'atlaspay-workspace-backup.json'));$('#backup-preview').onsubmit=attempt(async e=>{const file=e.target.elements.archive.files[0];if(file.size>75000000)throw Error('Backup too large');const result=await post('backup/preview',{archive:JSON.parse(await file.text())});$('#backup-summary').innerHTML=`<h2>Verified snapshot</h2><p>${esc(result.createdAt)} · ${result.payments} payments · ${result.invoices} invoices<br>Current workspace: ${result.currentPayments} payments</p><p>${esc(result.warning)}</p><label class="check-row"><input type="checkbox" id="restore-consent">Replace my current sandbox data with this snapshot</label><button id="restore-backup" class="primary wide">Restore verified snapshot</button>`;$('#restore-backup').onclick=attempt(async()=>{if(!$('#restore-consent').checked)throw Error('Confirm replacement of the displayed snapshot first');const response=await post('backup/restore',{previewId:result.previewId});await load();toast('Recovered. Safety copy retained: '+response.safetyCopy);});});
 }
}
